name: Hello World Practice

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"
      
      - name: Show Date and Time
        run: date
      
      - name: Show System Info
        run: |
          echo "OS: $(uname -s)"
          echo "User: $(whoami)"
          echo "Working Directory: $(pwd)"
      
      - name: Create a file
        run: echo "This is a test file" > test.txt
      
      - name: Show file content
        run: cat test.txt
